Repository yotsubo4242/mini-shell, pull requests merged in 2024-12, with the labels that each got.

#61 26 outout error when command not found(new)
  sed_test
  src/builtin/builtin.c
  src/exec/interpret.c
  test.sh
Labels: Priority: high, forbidden function

#74 45 unset
  src/builtin/builtin_exit.c
  src/builtin/builtin_unset.c
Labels: bug, Priority: high, builtin

#80 [#46] add: env test discription for NG's. don't have to be OK
  test.sh
Labels: builtin

#81 37 redirecting output
  Makefile
  include/prototype.h
  src/exec/interpret.c
  src/redirect/heredoc.c
  src/redirect/redirect.c
  src/xlib/xdup.c
  test.sh
Labels: bug, redirect

#92 49 fix pwd
  .gitignore
  include/prototype.h
  src/builtin/builtin_cd.c
  src/env/env.c
  src/env/hashmap.c
Labels: builtin

#96 [#84] modified: builtin_echo.c: delete duplicated header
  src/builtin/builtin_echo.c
  test.sh
Labels: bug, builtin

#98 86 fix exort a b c d
  src/builtin/builtin_export.c
  test.sh
Labels: bug, builtin, export

#99 [#97] done: word splitting tests
  test.sh
Labels: test

#100 89 fix export invalid identifire
  src/builtin/builtin_export.c
  test.sh
Labels: bug, builtin, export

#104 87 fix env empty string key
  test.sh
Labels: builtin, test, export, env

#103 93 fix builtin in pipe
  src/exec/interpret.c
  test.sh
Labels: bug, Priority: high, builtin

#105 85 exit 42
  Makefile
  include/prototype.h
  libft/Makefile
  libft/ft_strtol.c
  src/builtin/builtin_exit.c
  src/builtin/builtin_utils.c
  test.sh
Labels: bug, Priority: low, builtin, exit

#106 75 <<< needs syntax error
  Makefile
  include/prototype.h
  src/parse/parse.c
  src/parse/parse_utils.c
  src/parse/pipeline.c
  src/parse/simple_command.c
  test.sh
Labels: Priority: low, syntax

#133 [#124] ref: getset.c: adjust to norm
  src/getset/getset.c
Labels: norm

#130 117 norm include
  include/macro.h
  include/minishell.h
  include/prototype.h
  include/struct.h
  src/builtin/builtin_pwd.c
  src/env/env.c
  src/signal/signal.c
Labels: norm

#134 120 norm env
  Makefile
  include/prototype.h
  src/destruct/free_node_token.c
  src/env/env.c
  src/env/hashmap.c
  src/env/map.c
  src/env/map_utils.c
Labels: norm

#136 109 fix cleanup fd
  Makefile
  src/exec/interpret.c
  src/exec/pipe.c
  src/exec/search_path.c
  src/getset/getset.c
  src/redirect/heredoc.c
  src/redirect/redirect.c
Labels: bug, review

#138 119 norm destruct
  src/destruct/free_map.c
Labels: norm, review

#137 127 norm signal
  src/signal/signal.c
Labels: norm

#142 123 norm expand
  include/prototype.h
  src/expand/expand_heardoc.c
  src/expand/expand_variable.c
  src/expand/remove_quote.c
  src/expand/special_parameter.c
Labels: norm, review, expand

#141 121 norm error
  src/error/error.c
  src/error/syntax_error.c
Labels: norm, review

#140 128 norm tokenize
  Makefile
  include/prototype.h
  src/builtin/builtin.c
  src/destruct/free_node_token.c
  src/env/env.c
  src/tokenize/operators.c
  src/tokenize/tokenize.c
  src/tokenize/words.c
  src/tokenize/words_utils.c
Labels: norm, tokenize, review

#143 125 norm parse & xlib
  Makefile
  include/prototype.h
  src/parse/is_control_operator.c
  src/parse/pipeline.c
  src/test/env_test.c
  src/test/output_token.c
  src/xlib/xclose.c
Labels: norm

#146 [#83] done: buitltin_exit_extention
  src/builtin/builtin_exit.c
  test.sh
Labels: bug, builtin, exit

#147 145 fix heredoc memory leaks
  src/builtin/builtin.c
  src/destruct/free_node_token.c
  src/env/map_utils.c
  src/exec/exec_pipeline.c
Labels: review, leak, heredoc

#148 112 fix env not sorted in bash
  include/prototype.h
  src/builtin/builtin_export.c
  src/destruct/free_map.c
  src/env/map.c
  src/env/map_utils.c
Labels: bug, builtin, leak, export, env

#151 108 fix syntax error multiple times
  src/main.c
Labels: bug, syntax

#152 150 fix env var include space
  src/exec/token_list_to_argv.c
Labels: bug, export

#149 [#91] mod: heredoc c-D(EOF) last status to 0
  include/macro.h
  src/exec/exec.c
  src/main.c
  src/redirect/heredoc.c
  src/signal/signal.c
Labels: bug, signal, review
